config/routes.rb
Rails.application.routes.draw do
  resources :kudos
  root to: 'sessions#index'
  
  get "worker_sign_in" => "sessions#worker_sign_in"
  post "worker_sign_in" => "sessions#worker_login"
  get "worker_signed_out" => "sessions#worker_signed_out"
  get "new_worker" => "workers#new"

  get "supporter_sign_in" => "sessions#supporter_sign_in"
  get "supporter_signed_out" => "sessions#supporter_signed_out"
  get "new_supporter" => "supporters#new"
  post "supporter_sign_in" => "sessions#supporter_login"

  get "logout" => "sessions#destroy"
  get "remove_kudo" => "kudos#destroy"

  resources :supporters
  resources :workers
  resources :request_responses
  resources :financial_requests

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/financial_request.rb
class FinancialRequest < ApplicationRecord
    belongs_to :worker
    has_many :request_responses
    has_many :supporters, through: :request_responses

    # def self.sort_by_need
    #     Worker.order("stress DESC").map {|worker| FinancialRequest.where(worker_id: worker.id)}
    # end
end

app/controllers/financial_requests_controller.rb
class FinancialRequestsController < ApplicationController

    def show
        @request = FinancialRequest.find(params[:id])
        @worker = Worker.find(@request[:worker_id])
        @responses = RequestResponse.where(financial_request_id: @request.id, status:"pending")
    end

    def new
        @request = FinancialRequest.new
        @workers = Worker.all
    end

    def create
        @financial_request = FinancialRequest.new(request_params)
        
        if @financial_request.save
            redirect_to worker_path(@financial_request.worker_id)
        else
            flash[:error_messages] = @financial_request.errors.full_messages
            @financial_request
            render worker_path(@financial_request.worker_id)
        end
    end

    def edit
        @request = FinancialRequest.find(params[:id])
        session[:response] = params[:response]
        @response = RequestResponse.find(session[:response])
    end

    def update
        @request = FinancialRequest.find(params[:id])
        @response = RequestResponse.find(session[:response])
        # @request.money_needed -= @response.amount

        @response.update(status: "received")
        (@request.money_needed <= 0)? @request.status="fulfilled" : @request.status

        if @request.save
            session[:response] = ""
            redirect_to worker_path(@request.worker_id)
        else
            flash[:error_messages] = @request.errors.full_messages
            @request
            render worker_path(@request.worker_id)
        end
    end

    private

    def request_params
        params.require(:financial_request).permit(:money_needed, :title, :description, :venmo_name, :worker_id, :status, :updated_at)
    end
end

app/helpers/financial_requests_helper.rb
module FinancialRequestsHelper
end

app/views/financial_requests/_form.html.erb
<%=form_for financial_request do |f|%>
<table>

<tr>
<td id="req_form">
    <%=f.label :money_needed%>
</td>
<td>
    <%=f.number_field :money_needed%>    
</td>
</tr>

<tr>
<td id="req_form">
    <%=f.label :venmo_name%>
</td>
<td>
    <%=f.text_field :venmo_name%>
</td>
</tr>

<tr>
<td id="req_form">
    <%=f.label :title%>
</td>
<td>
    <%=f.text_field :title%>
</td>
</tr>

<tr>
<td id="req_form">
    <%=f.label :description%>
</td>
<td>
    <%=f.text_area :description %>
</td>
</tr>

<tr>
<td>
    <%=f.hidden_field :worker_id, :value=>worker_id%>
    <%=f.hidden_field :status, :value=>"active"%>
    <%=f.hidden_field :updated_at, :value=>DateTime.now%>
</td>
<td>
    <%=f.submit%>
</td>
</tr>
</table>
<%end%>

app/views/financial_requests/edit.html.erb
<h2 class="show_worker"> Update this request </h2>

<p>Confirming <%=@response.supporter.username%>'s response of $<%=@response.amount%></p>

<p><i>This is the updated amount you still need, and will refresh your request after you click update.</i></p>
<br><br>
<%= render partial: "financial_requests/form", locals: {financial_request: @request, worker_id: @request.worker_id, status: "updated"} %>

app/views/financial_requests/new.html.erb
<h2> Create a new request </h2>

<%if flash[:error_messages]%>
    <%flash[:error_messages].each do |message|%>
        <%=message%><br>
    <%end%><br>    
<%end%>
<br>
<br>
<%= render partial: "financial_requests/form", locals: {financial_request: @request, worker_id: @worker.id, status: "active"} %>

app/views/financial_requests/show.html.erb
<h1> <%= @request.title %> for <%= @worker.full_name %> </h1>
<br>
<%if @responses %>
    <% @responses.each do |response|%>

    <p>Supporter #<%= response.supporter_id %> sent you $<%= response.amount%> and says:<br>
    <%=response.message%> </p>

    <p><i>Please check your venmo account.  If you received this aid, please click this link:<br></i>
    <%= link_to "Confirm money received", edit_financial_request_path(id: response.financial_request_id, :response=> response)%></p>
    <br><br>

    <%end%>
<%else%>
    <p>You have no pending responses for this request.</p>
<%end%>