config/routes.rb
Rails.application.routes.draw do
  resources :kudos
  root to: 'sessions#index'
  
  get "worker_sign_in" => "sessions#worker_sign_in"
  post "worker_sign_in" => "sessions#worker_login"
  get "worker_signed_out" => "sessions#worker_signed_out"
  get "new_worker" => "workers#new"

  get "supporter_sign_in" => "sessions#supporter_sign_in"
  get "supporter_signed_out" => "sessions#supporter_signed_out"
  get "new_supporter" => "supporters#new"
  post "supporter_sign_in" => "sessions#supporter_login"

  get "logout" => "sessions#destroy"
  get "remove_kudo" => "kudos#destroy"

  resources :supporters
  resources :workers
  resources :request_responses
  resources :financial_requests

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/kudo.rb
class Kudo < ApplicationRecord
    # belongs_to :profession

    def self.select_kudos_by(profession)
        Kudo.where(profession: profession)
    end
end

app/controllers/kudos_controller.rb
class KudosController < ApplicationController
    
    def new
        @kudos = Kudo.new
        @professions = Profession.All 
        @supporter_id = session[:user_id]
    end

    def create
        @kudo = Kudo.new(kudo_params)
        if @kudo.save
            flash[:notice] = "Kudo added successfully!"
            redirect_to supporter_path(@kudo.supporter_id)
        else
            flash[:error_messages] = @kudo.errors.full_messages
            @kudo
            render supporter_path(@kudo.supporter_id)
        end
    end

    def show

    end

    def destroy
        @remove = Kudo.find(params[:format])
        @remove.destroy
        redirect_to workers_path
    end

    private

    def kudo_params
        params.require(:kudo).permit(:profession, :title, :comment, :supporter_id)
    end
end

app/helpers/kudos_helper.rb
module KudosHelper
end

app/views/kudos/_form.html.erb
<table class="kudos_form">
<%=form_for kudos do |f|%>
<tr>
<td>
    <%=f.label :profession%>
</td>
<td>
    <%=f.collection_select :profession, professions, :category, :category%><br>
</td>
</tr>
<tr>
<td>
    <%=f.label :title%>
</td>
<td>
    <%=f.text_field :title%><br>
</td>
</tr>
<tr>
<td>
    <%=f.label :comment%>
</td>
<td>
    <%=f.text_area :comment%><br>
</td>
</tr>
<tr>
<td>
    <%=f.hidden_field :supporter_id, :value=>supporter_id%>
    <%=f.submit "Give Kudos!"%>
</td>
</tr>
<%end%>
</table>

app/views/kudos/_show.html.erb
<h3 id="kudos">Title: <%=kudos.title%><br></h3>
<p><%=kudos.comment%></p>
<p><i>If this comment is offensive, or negative, please <%=link_to "remove it", remove_kudo_path(kudos.id)%></i></p>
<br><br><br>