config/routes.rb
Rails.application.routes.draw do
  resources :kudos
  root to: 'sessions#index'
  
  get "worker_sign_in" => "sessions#worker_sign_in"
  post "worker_sign_in" => "sessions#worker_login"
  get "worker_signed_out" => "sessions#worker_signed_out"
  get "new_worker" => "workers#new"

  get "supporter_sign_in" => "sessions#supporter_sign_in"
  get "supporter_signed_out" => "sessions#supporter_signed_out"
  get "new_supporter" => "supporters#new"
  post "supporter_sign_in" => "sessions#supporter_login"

  get "logout" => "sessions#destroy"
  get "remove_kudo" => "kudos#destroy"

  resources :supporters
  resources :workers
  resources :request_responses
  resources :financial_requests

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/worker.rb
class Worker < ApplicationRecord
    has_many :financial_requests
    has_many :request_responses, through: :financial_requests

    validates :username, :full_name, :password_digest, presence: true
    validates :username, uniqueness: true
    
    has_secure_password

    def statistics
        self.request_responses.sum {|resp| resp.amount}
    end

    # @worker.password_digest = BCrypt::Password.create(worker_params[:password_digest])

end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
    before_action :require_login
    before_action :is_worker?
    skip_before_action :require_login, only: [:new, :create]

    def index
        profession = Profession.find(current_user.field_of_work)
        @mykudos = Kudo.select_kudos_by(profession.category)
        @generalkudos = Kudo.select_kudos_by("General")
    end

    def new
        @worker = Worker.new
        @neighborhoods = Neighborhood.all 
        @professions = Profession.all 
    end

    def create
        @worker = Worker.new(worker_params)
        if @worker.save
            session[:user_id] = @worker.id
            session[:user_type] = "worker"
            redirect_to worker_path(@worker.id)
        else
            flash[:error_messages] = @worker.errors.full_messages
            @worker
            @neighborhoods = Neighborhood.all 
            @professions = Profession.all
            render :new 
        end
    end

    def edit
    end

    def update
    end

    def show
        @worker = current_user
        session[:user_id] = @worker.id
        @request = FinancialRequest.new
        @stats = @worker.statistics
        @all_requests = @worker.financial_requests.order("created_at DESC")
        @professions = Profession.all
    end

    private

    def worker_params
        params.require(:worker).permit(:username, :password, :confirm_password, :full_name, :stress, :dependents, :field_of_work, :neighborhood)
    end

    def require_login
        return head(:forbidden) unless session.include? :user_id
    end

    def is_worker?
        user_type == "worker"
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%=form_for worker do |f| %>
<%=f.label :username %>
<%=f.text_field :username %><br><br>
<%=f.label "Password"%>
<%=f.password_field :password%><br><br>
<%=f.label :full_name %>
<%=f.text_field :full_name %><br><br>
<%=f.label "Stress Level"%> &#128556
<%=f.range_field :stress, :in => 0..5, :step => '.5' %> &#128561 <br><br>
<%=f.label :dependents %>
<%=f.number_field :dependents, :in => 0..30, :step => '1'%><br><br>
Profession <%=f.collection_select :field_of_work, @professions, :id, :category%><br><br>
Neighborhood <%=f.collection_select :neighborhood, @neighborhoods, :id, :region%><br><br>
<%=f.submit%>
<%end%>

app/views/workers/index.html.erb
<h1> Welcome Essential Workers </h1>
<h2 id="display"><i> We couldn't do it without you!</i></h2>

<br><br>
<h2 id="display">Kudos!</h2>
<br><br>


<div class="body">
<table>
<th><h3>About my field:</h3></th>
<th><h3>General Kudos for essential workers:</h3></th>
<tr>
<td>
<%@mykudos.each do |kudo|%>
    <p><%=render partial: "kudos/show", locals: {kudos: kudo} %></p>
<%end%>
</td>
<td>
<%@generalkudos.each do |kudo|%>
    <p><%=render partial: "kudos/show", locals: {kudos: kudo} %></p>
<%end%>
</td>
</tr>
</table>
</div>

app/views/workers/new.html.erb
<h1> Register a new Essential Worker </h1>
<br>
<br>

<%= render partial: "form", locals: {worker: @worker} %>

app/views/workers/show.html.erb
<h1> Welcome, <%= @worker.full_name%> </h1>
<p><i>You have received $<%=@stats%> from your supporters!</i></p>
<br><br><br>

<h2 class="show_worker"> What's good! </h2>
<p><%=link_to "Check out some nice things people have said", workers_path%></p>
<br><br><br>

<table>
<tr>
<th><h2> Create a new financial request </h2></th>
<th><h2> See your requests: </h2></th>
</tr>

<tr>
<td>
<%= render partial: "financial_requests/form", locals: {financial_request: @request, worker_id: @worker.id} %>
<br><br><br>
</td>

<td>
<% @all_requests.each do |request|%>
<p>$<%=link_to request.money_needed, financial_request_path(request.id)%> requested on <%=request.created_at%><br>
<%=request.title%> | <%=request.description%><br>
Status: <b><%=request.status%></b></p>
<%end%>
</td>
</tr>
</table>